### ISSUE TITLE
Can't output reactors vapor using pipes of immersive engineers

### ISSUE THREAD

**Issue by iceleon** [ZeroNoRyouki/ExtremeReactors2-issues#14]
i tried use only pipes or pipes with pump but i can't tak out the vapor.
i tried use the 2 different ports but i don't have succeed.
but i can input wather usim pumps, tubes and a passive forg fluid port

**Comment by ZeroNoRyouki** [comment]
What port are you using? It should be a Reactor (active or passive depending on the pipe) FORGE Fluid Port, not the Mekanism one

I've just tested it with a Reactor Active Forge Fluid Port and Immersive Engineers Fluid Pipes and vapor is sent out:

![2020-12-06_11 28 36](https://user-images.githubusercontent.com/7107662/101277681-73b8d280-37b6-11eb-9ce2-0fd0d8932242.png)

The (Mekanism) tank is full of steam

**Comment by iceleon** [comment]
Sorry man, i'm dumb i forgot to use the wrench to changing the ports for output. all my ports was input
