### ISSUE TITLE
ZeroCore Update null pointed error.

### ISSUE THREAD

**Issue by Gaiyamato** [ZeroNoRyouki/ExtremeReactors2-issues#15]
Using the latest version of ZeroCore mod leads to a null pointer for mod_ores error.

![ExtremeReactors bug](https://user-images.githubusercontent.com/63906224/101342213-5aa74300-38d6-11eb-9562-c7feb58ba1b5.PNG)

**Comment by ZeroNoRyouki** [comment]
Hi, are you also using the last ER version?
thank you

**Comment by Gaiyamato** [comment]
> Hi, are you also using the last ER version?
> thank you
> 
> PS: could you post the crash log on a nopaste website please?

It didn't crash, it doesn't start up. there isn't anything in the crash log. 

Yes, using latest XR2 version for MC 16.4, Forge 35.1.7.

**Comment by Gaiyamato** [comment]
Issue resolved by simply updating to current versions.
