### ISSUE TITLE
Gui does not show up if any item is held in hand. 

### ISSUE THREAD

**Issue by MuteTiefling** [ZeroNoRyouki/ExtremeReactors2-issues#3]
Version: ExtremeReactors2-1.16.3-2.0.1

![2020-11-04_22 29 09](https://user-images.githubusercontent.com/9543430/98194361-31695080-1eed-11eb-9d4b-160caf9ef309.png)

Reactor is formed, but if I have a sword in hand, or any other tool, I can't access the gui. Works fine with an empty hand.

**Comment by ZeroNoRyouki** [comment]
Hi, fixed the hand thing but I'm also noting that you have the "missing-texture" texture rendeing in the fuel rods. Do you have any "texture not found" or similar errors in your logs?

**Comment by MuteTiefling** [comment]
Thanks for the quick fix on these issues!

[latest.log](https://github.com/ZeroNoRyouki/ExtremeReactors2-issues/files/5494171/latest.log)

Here's my log for that session. There's... a lot of texture errors, though I'm not specifically seeing any from your mod. I also didn't look very hard, so if you want to take a gander, feel free.

**Comment by ZeroNoRyouki** [comment]
Thank you. Did you notice, in game, any other textures missing or it's only mine in the fuel rod?

**Comment by MuteTiefling** [comment]
I didn't notice any others, no.

**Comment by ZeroNoRyouki** [comment]
Closed in ER/ZC 2.0.2
