### ISSUE TITLE
Redstone Port - Energy Stored does not seem to work

### ISSUE THREAD

**Issue by MuteTiefling** [ZeroNoRyouki/ExtremeReactors2-issues#4]
Version: ExtremeReactors2-1.16.3-2.0.1

I'm always getting a signal of 15 from this, no matter what I set it to. 

For instance, right now, the buffer is full, the port is set to Active Below 100%. Redstone signal is 15. 

If I drain the power, redstone signal from the port remains 15 which is what I'd actually expect here. But if I then change it to Active Above 0% it stays on.

**Comment by ZeroNoRyouki** [comment]
Hi, found the problem and fixed it. It should be out later today.
Thank you for letting me known.

**Comment by ZeroNoRyouki** [comment]
Closed in ER 2.0.2
