### ISSUE TITLE
1.16.4, Ore gen not disabling when set in config to not gen

### ISSUE THREAD

**Issue by BedrockLegends** [ZeroNoRyouki/ExtremeReactors2-issues#8]
![2020-11-22_17 08 54](https://user-images.githubusercontent.com/48525410/99919852-8c6cb700-2ce5-11eb-9625-14f5784dee89.png)

When I disable The Ore gen using the config, nothing seems to happen

**Comment by ZeroNoRyouki** [comment]
Hi, did you disable the general generation option or one of the three ore-specific options?
Did you reastart your game/server after changing the config file?
Is that a newly generated chunk or an old (pre-config change) one? Old chunks are not effected by the config change
Thank you
Z

**Comment by BedrockLegends** [comment]
I disable them through the config and its only the yellowrite ore thats genning as I disabled the other ore already

**Comment by Sunekaer** [comment]
Hi, i have the same issue.
`yelloriteOreEnableWorldGen = false` but yellorite is still spawning
Config was generated, then changed, then deleted the world and generated a new onme

**Comment by BedrockLegends** [comment]
I am mainly disabling ore for my WIP sky pack

**Comment by ZeroNoRyouki** [comment]
I've found the problem and fixed it. An update release should be out later today.
Thank for the reports guys

**Comment by ZeroNoRyouki** [comment]
2.0.9 is out
