### ISSUE TITLE
Incompatible with refined storage

### ISSUE THREAD

**Issue by Mewtwoy** [ZeroNoRyouki/ExtremeReactors2-issues#9]
https://pastebin.com/jMtPNsPv

Ghost blocks are created when reactor fluid port blocks are broken.
They cannot be fully removed in creative, only survival, and when done so, the game crashes.

Happens even when absolutely zero blocks from refined storage are being used close to it.

**Comment by ZeroNoRyouki** [comment]
Problem found, fix incoming
Thanks for the report

**Comment by ZeroNoRyouki** [comment]
Fixed in 2.0.8
